### ISSUE TITLE
Use GCP method to print instead creating all formula

### ISSUE THREAD

**Issue by pmfernandes** [PrimaverabssDeveloper/Community#1]
Hi @NunoPeixotoPrimavera

I think that you can use GCP method, available in public engine, to print?
Using that you don't have to worry about legal changes on formula.

What do you think? 😉 

https://github.com/PrimaverabssDeveloper/Community/blob/bb24fe97b2b8d6318c282fe232bd7f59705ef6be/ImpressaoMapasDePaginaWeb/WebERPPrintSample/WebERPPrint.aspx.cs#L40

**Comment by NunoPeixotoPrimavera** [comment]
@pmfernandes 
This is a simple example that uses only platform (StdPlatBS) methods, because to use the engine (ErpBS), a specific license (TEC-MTR) is required.

But yes, it's a good idea ;)
Thanks
